# Generated by Django 5.0.9 on 2026-09-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("dictionaries", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Ф.И.Ш. (полностью)"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "specialty_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Специальность по диплому об учёной степени",
                    ),
                ),
                (
                    "diploma_series",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Серия диплома"
                    ),
                ),
                (
                    "diploma_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер диплома"
                    ),
                ),
                (
                    "foreign_university_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Зарубежный ОТМ, присвоивший степень",
                    ),
                ),
                (
                    "hire_order_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="№ приказа о приёме"
                    ),
                ),
                (
                    "hire_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приказа о приёме"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Работает сейчас"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teachers",
                        to="core.department",
                        verbose_name="Кафедра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherPeriodSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stavka",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=4, verbose_name="Ставка"
                    ),
                ),
                (
                    "academic_degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dictionaries.academicdegree",
                        verbose_name="Учёная степень на момент отчёта",
                    ),
                ),
                (
                    "academic_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dictionaries.academictitle",
                        verbose_name="Учёное звание на момент отчёта",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.employmenttype",
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.position",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_snapshots",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_snapshots",
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок статуса ППС за период",
                "verbose_name_plural": "Снимки статуса ППС за период",
                "ordering": [
                    "reporting_period",
                    "employment_type__sort_order",
                    "teacher__full_name",
                ],
                "unique_together": {("teacher", "reporting_period")},
            },
        ),
    ]
