# Generated by Django 5.0.9 on 2026-09-23 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="diploma_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teachers/diplomas/",
                verbose_name="Скан диплома об учёной степени (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Заводится кафедрой через действие «Создать логин» в списке преподавателей — даёт доступ в личный кабинет, где преподаватель сам вносит свои показатели.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Логин в системе",
            ),
        ),
    ]
