# Generated by Django 5.0.9 on 2026-10-08 17:51

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0002_alter_country_category"),
        ("staff", "0002_teacher_diploma_file_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="citizenship_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="dictionaries.country",
                verbose_name="Гражданство (для иностранцев)",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="foreign_degree_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOP100", "TOP-100"),
                    ("TOP300", "TOP-300"),
                    ("TOP500", "TOP-500"),
                    ("TOP1000", "TOP-1000"),
                    ("other", "Вне рейтинга TOP-1000"),
                ],
                help_text="Заполняется, только если степень получена за рубежом.",
                max_length=10,
                verbose_name="Рейтинг зарубежного ОТМ, присвоившего степень",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="foreign_master_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOP100", "TOP-100"),
                    ("TOP300", "TOP-300"),
                    ("TOP500", "TOP-500"),
                    ("TOP1000", "TOP-1000"),
                    ("other", "Вне рейтинга TOP-1000"),
                ],
                max_length=10,
                verbose_name="Рейтинг зарубежного ОТМ (магистратура)",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="foreign_master_university",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Зарубежный ОТМ, где окончена магистратура",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="hire_order_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teachers/orders/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Скан приказа о приёме (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_foreign_citizen",
            field=models.BooleanField(
                default=False, verbose_name="Иностранный гражданин"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="master_diploma_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teachers/master_diplomas/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Скан зарубежного диплома магистра (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Должна совпадать с паспортом (лист 1,2).",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="diploma_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teachers/diplomas/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Скан диплома об учёной степени / звании (PDF)",
            ),
        ),
    ]
