# Generated by Django 5.0.9 on 2026-09-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.Ш.")),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("bakalavriat", "Бакалавриат"),
                            ("magistratura", "Магистратура"),
                        ],
                        default="bakalavriat",
                        max_length=20,
                        verbose_name="Уровень обучения",
                    ),
                ),
                (
                    "citizenship_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="dictionaries.country",
                        verbose_name="Гражданство",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="core.department",
                        verbose_name="Кафедра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Graduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.Ш.")),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(verbose_name="Год выпуска"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="graduates",
                        to="core.department",
                        verbose_name="Кафедра",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graduate_record",
                        to="students.student",
                        verbose_name="Запись студента (если есть)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выпускник",
                "verbose_name_plural": "Выпускники",
                "ordering": ["-graduation_year", "full_name"],
            },
        ),
    ]
