# Generated by Django 5.0.9 on 2026-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "high_income_developed",
                        "Развитая страна с высоким доходом (список Всемирного банка)",
                    ),
                    ("central_asia", "Страна Центральной Азии"),
                    ("other", "Другая страна"),
                ],
                default="other",
                max_length=30,
                verbose_name="Категория (для отчётов по мобильности)",
            ),
        ),
    ]
