# Generated by Django 5.0.9 on 2026-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0002_alter_country_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_home_country",
            field=models.BooleanField(
                default=False,
                help_text="Студенты и преподаватели с этим гражданством не считаются иностранцами.",
                verbose_name="Страна вуза (Узбекистан)",
            ),
        ),
    ]
