# Generated by Django 5.0.9 on 2026-09-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название (полное)"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Короткое название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Университет",
                "verbose_name_plural": "Университеты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название факультета"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Короткое название"
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculties",
                        to="core.university",
                        verbose_name="Университет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
                "ordering": ["name"],
                "unique_together": {("university", "name")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название кафедры"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Короткое название"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="core.faculty",
                        verbose_name="Факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кафедра",
                "verbose_name_plural": "Кафедры",
                "ordering": ["name"],
                "unique_together": {("faculty", "name")},
            },
        ),
    ]
