# Generated by Django 5.0.9 on 2026-10-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0003_home_country_and_active"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Учится сейчас"),
        ),
        migrations.AlterField(
            model_name="student",
            name="citizenship_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="dictionaries.country",
                verbose_name="Гражданство",
            ),
        ),
    ]
