# Generated by Django 5.0.9 on 2026-09-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicDegree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Учёная степень",
                "verbose_name_plural": "Учёные степени",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учёное звание",
                "verbose_name_plural": "Учёные звания",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название страны"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "high_income_developed",
                                "Юқори даромадли ривожланган мамлакат",
                            ),
                            ("central_asia", "Марказий Осиё давлати"),
                            ("other", "Бошқа давлат"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Категория (для отчётов по мобильности)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок в отчёте"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип занятости",
                "verbose_name_plural": "Типы занятости",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название должности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность (лавозим)",
                "verbose_name_plural": "Должности (лавозимлар)",
                "ordering": ["name"],
            },
        ),
    ]
