# Generated by Django 5.0.9 on 2026-09-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        ("students", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "foreign_international",
                                "Зарубежные / международные организации",
                            ),
                            ("state_program", "Государственные научные программы"),
                            ("business_contract", "Хоздоговорные заказы"),
                        ],
                        max_length=30,
                        verbose_name="Источник средств",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundings",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundings",
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привлечённые средства",
                "verbose_name_plural": "Привлечённые средства",
            },
        ),
        migrations.CreateModel(
            name="GraduateEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entrepreneur_or_founder", "ИП / учредитель"),
                            (
                                "employed_state_or_business",
                                "Трудоустроен (гос. орган / хоз. субъект)",
                            ),
                            (
                                "further_education_or_exempt",
                                "Продолжает учёбу / декрет / инвалидность / самозанят",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Статус занятости",
                    ),
                ),
                (
                    "months_to_employment",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(3, "3"), (6, "6"), (12, "12")],
                        null=True,
                        verbose_name="Через сколько месяцев трудоустроен",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Средний месячный доход",
                    ),
                ),
                (
                    "graduate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to="students.graduate",
                        verbose_name="Выпускник",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduate_employment",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трудоустройство выпускника",
                "verbose_name_plural": "Трудоустройство выпускников",
            },
        ),
        migrations.CreateModel(
            name="NationalAvgSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Средняя номинальная зарплата по РУз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Средняя зарплата по стране (Госкомстат)",
                "verbose_name_plural": "Средняя зарплата по стране (Госкомстат)",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Название"
                    ),
                ),
                (
                    "patent_type",
                    models.CharField(
                        choices=[
                            ("invention", "Изобретение"),
                            ("utility_model", "Полезная модель"),
                            ("industrial_design", "Промышленный образец"),
                            ("selection_achievement", "Селекционное достижение"),
                        ],
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "registered_in_scopus",
                    models.BooleanField(default=False, verbose_name="Учтён в Scopus"),
                ),
                (
                    "has_license_agreement",
                    models.BooleanField(
                        default=False, verbose_name="Есть лицензионный договор"
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patents",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Патент / объект интеллектуальной собственности",
                "verbose_name_plural": "Патенты / объекты интеллектуальной собственности",
            },
        ),
        migrations.CreateModel(
            name="PatentAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reports.patent"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.teacher"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор патента",
                "verbose_name_plural": "Авторы патентов",
                "unique_together": {("patent", "teacher")},
            },
        ),
        migrations.AddField(
            model_name="patent",
            name="authors",
            field=models.ManyToManyField(
                related_name="patents",
                through="reports.PatentAuthor",
                to="staff.teacher",
                verbose_name="Авторы",
            ),
        ),
        migrations.CreateModel(
            name="PostgradDefense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("PhD", "PhD (фалсафа доктори)"),
                            ("DSc", "DSc (фан доктори)"),
                        ],
                        max_length=5,
                        verbose_name="Степень",
                    ),
                ),
                (
                    "defended_full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ф.И.Ш. соискателя"
                    ),
                ),
                (
                    "advisor_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postgrad_defenses",
                        to="staff.teacher",
                        verbose_name="Научный руководитель",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postgrad_defenses",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Защита диссертации (под руководством)",
                "verbose_name_plural": "Защиты диссертаций (под руководством)",
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название журнала"
                    ),
                ),
                (
                    "publish_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год публикации"
                    ),
                ),
                (
                    "publish_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Месяц публикации"
                    ),
                ),
                (
                    "article_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Название статьи"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Язык публикации"
                    ),
                ),
                (
                    "scopus_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Ссылка Scopus"
                    ),
                ),
                (
                    "quartile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Квартиль",
                    ),
                ),
                (
                    "citation_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top1", "Top 1% most cited"),
                            ("top10", "Top 10% most cited"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Топ по цитируемости",
                    ),
                ),
                (
                    "citations_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Число цитирований (Scopus)"
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="staff.teacher",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация (Scopus)",
                "verbose_name_plural": "Публикации (Scopus)",
                "ordering": ["-publish_year", "-publish_month"],
            },
        ),
        migrations.CreateModel(
            name="ReputationVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rating_org_expert", "Эксперт THE / QS / ARWU"),
                            (
                                "national_qa_agency_expert",
                                "Эксперт нац. агентства по качеству образования",
                            ),
                            (
                                "foreign_partner_staff",
                                "Сотрудник зарубежного вуза-партнёра",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Источник голосов",
                    ),
                ),
                (
                    "votes_count",
                    models.PositiveIntegerField(verbose_name="Число голосов"),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_votes",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_votes",
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос за международную репутацию",
                "verbose_name_plural": "Голоса за международную репутацию",
            },
        ),
        migrations.CreateModel(
            name="StudentMobility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        max_length=10,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("exchange", "Программа обмена"),
                            ("joint_program", "Совместная образовательная программа"),
                        ],
                        max_length=20,
                        verbose_name="Тип программы",
                    ),
                ),
                (
                    "partner_rank",
                    models.CharField(
                        choices=[
                            ("TOP100", "TOP-100"),
                            ("TOP300", "TOP-300"),
                            ("TOP500", "TOP-500"),
                            ("TOP1000", "TOP-1000"),
                            ("other", "Вне рейтинга"),
                        ],
                        max_length=10,
                        verbose_name="Рейтинг партнёрского вуза",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_mobility",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_records",
                        to="students.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Академическая мобильность студента",
                "verbose_name_plural": "Академическая мобильность студентов",
            },
        ),
        migrations.CreateModel(
            name="TeacherMobility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        max_length=10,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "partner_institution_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Партнёрский вуз"
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_mobility",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_records",
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Международная мобильность ППС",
                "verbose_name_plural": "Международная мобильность ППС",
            },
        ),
        migrations.CreateModel(
            name="IndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("teacher", "Преподаватель"),
                            ("student", "Студент"),
                            ("graduate", "Выпускник"),
                            ("department", "Кафедра"),
                        ],
                        max_length=20,
                        verbose_name="Тип субъекта",
                    ),
                ),
                ("subject_id", models.PositiveIntegerField(verbose_name="ID субъекта")),
                (
                    "indicator_code",
                    models.CharField(
                        help_text="Например: sheet_1_3_top100_degree_count",
                        max_length=100,
                        verbose_name="Код показателя",
                    ),
                ),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Числовое значение",
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Текстовое значение"
                    ),
                ),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Путь к подтверждающему документу",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель (гибкий, вне основной схемы)",
                "verbose_name_plural": "Показатели (гибкие, вне основной схемы)",
                "unique_together": {
                    ("reporting_period", "subject_type", "subject_id", "indicator_code")
                },
            },
        ),
        migrations.CreateModel(
            name="TeacherHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "h_index",
                    models.PositiveIntegerField(verbose_name="Индекс Хирша (Scopus)"),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hindex_records",
                        to="workflow.reportingperiod",
                        verbose_name="Отчётный период",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hindex_records",
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "H-индекс",
                "verbose_name_plural": "H-индексы",
                "unique_together": {("teacher", "reporting_period")},
            },
        ),
    ]
