# Generated by Django 5.0.9 on 2026-09-23 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        help_text="Например: 2026-mart",
                        max_length=50,
                        verbose_name="Метка периода",
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        verbose_name="Дата, на которую формируется отчёт (holatiga)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик (кафедра вводит данные)"),
                            ("submitted", "Отправлено на согласование"),
                            ("approved", "Утверждено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Утверждено"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reporting_periods",
                        to="core.department",
                        verbose_name="Кафедра",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправил на согласование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчётный период",
                "verbose_name_plural": "Отчётные периоды",
                "ordering": ["-period_date"],
                "unique_together": {("department", "period_label")},
            },
        ),
    ]
