# Generated by Django 5.0.9 on 2026-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingperiod",
            name="staff_units",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Выделенные штатные единицы (лист 5)",
            ),
        ),
        migrations.AddField(
            model_name="reportingperiod",
            name="total_graduates_count",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Общее число выпускников (листы 4,1 и 4,2)",
            ),
        ),
        migrations.AddField(
            model_name="reportingperiod",
            name="total_students_count",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Общее число студентов бакалавриата и магистратуры (листы 3,2 и 3,3)",
            ),
        ),
        migrations.AlterField(
            model_name="reportingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик (преподаватели вводят данные)"),
                    ("submitted", "Отправлено на согласование"),
                    ("approved", "Утверждено"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
