# Generated by Django 5.0.9 on 2026-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funding",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fundings/",
                verbose_name="Договор / квитанция (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="patents/",
                verbose_name="Документ, подтверждающий патент (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="article_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="publications/",
                verbose_name="Электронный PDF статьи",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="department_co_authors_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Если статью написали несколько сотрудников кафедры вместе, в своде по квартилям (лист 2,1) каждому засчитывается доля 1/N — как в исходной методике министерства (там встречаются значения вида 0.33, 0.5, 0.66).",
                verbose_name="Число соавторов-сотрудников этой кафедры",
            ),
        ),
    ]
