# Generated by Django 5.0.9 on 2026-10-08 17:51

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_publication_authors(apps, schema_editor):
    """Раньше у статьи был один автор (teacher) и число соавторов-сотрудников
    кафедры. Теперь авторы — список, а доля считается от общего числа авторов:
    переносим автора в список, старое число соавторов — в authors_total."""
    Publication = apps.get_model("reports", "Publication")
    PublicationAuthor = apps.get_model("reports", "PublicationAuthor")
    for pub in Publication.objects.all():
        PublicationAuthor.objects.get_or_create(publication=pub, teacher_id=pub.teacher_id)
        if (pub.department_co_authors_count or 1) > 1:
            pub.authors_total = pub.department_co_authors_count
            pub.save(update_fields=["authors_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_funding_document_file_patent_document_file_and_more"),
        ("staff", "0003_teacher_foreign_and_documents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patent",
            options={
                "verbose_name": "Патент / свидетельство",
                "verbose_name_plural": "Патенты / свидетельства",
            },
        ),
        migrations.AlterModelOptions(
            name="patentauthor",
            options={
                "verbose_name": "Автор патента",
                "verbose_name_plural": "Авторы патента",
            },
        ),
        migrations.AddField(
            model_name="funding",
            name="contract_info",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Договор / приказ: номер, дата, заказчик",
            ),
        ),
        migrations.AddField(
            model_name="graduateemployment",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="graduates/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Справка с места работы (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="authors_total",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Включая авторов из других организаций. Каждому автору кафедры засчитывается доля 1/N.",
                null=True,
                verbose_name="Общее число авторов",
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.AddField(
            model_name="patent",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Номер патента / свидетельства"
            ),
        ),
        migrations.AddField(
            model_name="postgraddefense",
            name="defense_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата защиты"),
        ),
        migrations.AddField(
            model_name="postgraddefense",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="defenses/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Подтверждающий документ (протокол / диплом, PDF)",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="authors_total",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Включая авторов из других организаций. Каждому автору кафедры засчитывается доля 1/N: при 2 авторах — по 0.5, при 3 — по 0.33.",
                null=True,
                verbose_name="Общее число авторов статьи",
            ),
        ),
        migrations.AddField(
            model_name="reputationvote",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reputation/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Список респондентов / подтверждение (PDF, Excel)",
            ),
        ),
        migrations.AddField(
            model_name="reputationvote",
            name="note",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Примечание (организация, респонденты)",
            ),
        ),
        migrations.AddField(
            model_name="studentmobility",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="student_mobility/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Приказ / подтверждение (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="studentmobility",
            name="order_info",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Приказ ректора: номер и дата"
            ),
        ),
        migrations.AddField(
            model_name="studentmobility",
            name="partner_institution_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Партнёрский вуз"
            ),
        ),
        migrations.AddField(
            model_name="teacherhindex",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="hindex/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Скриншот профиля Scopus (PDF/PNG)",
            ),
        ),
        migrations.AddField(
            model_name="teacherhindex",
            name="scopus_profile_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ссылка на профиль Scopus"
            ),
        ),
        migrations.AddField(
            model_name="teachermobility",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="mobility/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Приказ / сертификат (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="teachermobility",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Окончание"),
        ),
        migrations.AddField(
            model_name="teachermobility",
            name="order_info",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Приказ ректора: номер и дата"
            ),
        ),
        migrations.AddField(
            model_name="teachermobility",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Начало"),
        ),
        migrations.AlterField(
            model_name="funding",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Сумма (сум)"
            ),
        ),
        migrations.AlterField(
            model_name="funding",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fundings/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Договор / квитанция (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="authors",
            field=models.ManyToManyField(
                related_name="patents",
                through="reports.PatentAuthor",
                to="staff.teacher",
                verbose_name="Авторы — сотрудники кафедры",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="patents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Документ, подтверждающий патент (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="patent_type",
            field=models.CharField(
                choices=[
                    ("invention", "Изобретение"),
                    ("utility_model", "Полезная модель"),
                    ("industrial_design", "Промышленный образец"),
                    ("selection_achievement", "Селекционное достижение"),
                    ("software_certificate", "Свидетельство на программу/БД (DGU)"),
                ],
                max_length=30,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="patentauthor",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="postgraddefense",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("PhD", "PhD (доктор философии)"),
                    ("DSc", "DSc (доктор наук)"),
                ],
                max_length=5,
                verbose_name="Степень",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="article_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="publications/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "zip",
                            "rar",
                        ]
                    ),
                    apps.core.validators.validate_document_size,
                ],
                verbose_name="Электронный PDF статьи",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entered_publications",
                to="staff.teacher",
                verbose_name="Кто внёс запись",
            ),
        ),
        migrations.AlterField(
            model_name="studentmobility",
            name="partner_rank",
            field=models.CharField(
                choices=[
                    ("TOP100", "TOP-100"),
                    ("TOP300", "TOP-300"),
                    ("TOP500", "TOP-500"),
                    ("TOP1000", "TOP-1000"),
                    ("other", "Вне рейтинга TOP-1000"),
                ],
                max_length=10,
                verbose_name="Рейтинг партнёрского вуза",
            ),
        ),
        migrations.AlterField(
            model_name="studentmobility",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("exchange", "Программа обмена (лист 3,3)"),
                    (
                        "joint_program",
                        "Совместная образовательная программа (лист 3,5)",
                    ),
                ],
                max_length=20,
                verbose_name="Тип программы",
            ),
        ),
        migrations.AlterField(
            model_name="teachermobility",
            name="direction",
            field=models.CharField(
                choices=[
                    ("outbound", "Outbound (выезд за рубеж)"),
                    ("inbound", "Inbound (приём зарубежного преподавателя)"),
                ],
                max_length=10,
                verbose_name="Направление",
            ),
        ),
        migrations.CreateModel(
            name="PublicationAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.publication",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор статьи",
                "verbose_name_plural": "Авторы статьи",
                "unique_together": {("publication", "teacher")},
            },
        ),
        migrations.AddField(
            model_name="publication",
            name="authors",
            field=models.ManyToManyField(
                related_name="publications",
                through="reports.PublicationAuthor",
                to="staff.teacher",
                verbose_name="Авторы — сотрудники кафедры",
            ),
        ),
        migrations.RunPython(copy_publication_authors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="publication",
            name="department_co_authors_count",
        ),
    ]
